Update create_trophy.yml

diff --git a/.github/workflows/create_trophy.yml b/.github/workflows/create_trophy.yml
--- a/.github/workflows/create_trophy.yml
+++ b/.github/workflows/create_trophy.yml
@@ -1,50 +1,47 @@
 name: create_trophy
+
 on:
   schedule:
-     - cron: "0 3 * * *"
-  # allows to manually run the job at any time
+    - cron: "0 3 * * *"
   workflow_dispatch:
-  
-  # run on every push on the master branch
   push:
     branches:
-    - main
+      - main
 
 jobs:
   create-trophy:
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout this repo
+        uses: actions/checkout@v4
 
-    - name: Checkout this repo
-      uses: actions/checkout@v4
+      - name: Generate trophy
+        id: trophy
+        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
+        with:
+          username: ${{ github.repository_owner }}
+          file: dist/trophy.svg
+          token: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Generate trophy
-      id: trophy
-      uses: Erik-Donath/github-profile-trophy@feature/generate-svg
-      with:
-        username: ${{ github.repository_owner }}
-        output_path: ./trophy.svg
-        token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Debug workspace
+        run: |
+          pwd
+          find . -type f
 
-    - name: Debug workspace
-      run: |
-        pwd
-        find . -type f
+      - name: Verify SVG generated
+        run: |
+          if [ -f dist/trophy.svg ]; then
+              echo "SVG exists ($(wc -c < dist/trophy.svg) Bytes)"
+              file dist/trophy.svg
+          else
+              echo "SVG failed to generate"
+              exit 1
+          fi
 
-    - name: Verify SVG generated
-      run: |
-        if [ -f dist/trophy.svg ]; then
-          echo "SVG exists ($(wc -c < dist/trophy.svg) Bytes)"
-          file dist/trophy.svg
-        else
-          echo "SVG failed to generate"
-          exit 1
-        fi
-
-    - name: push_github-contribution-trophy.svg # to the output branch
-      uses: crazy-max/ghaction-github-pages@v3.1.0
-      with:
-        target_branch: snake
-        build_dir: dist
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Push trophy to output branch
+        uses: crazy-max/ghaction-github-pages@v4
+        with:
+          target_branch: snake
+          build_dir: dist
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
